import type { AnalysisResult } from "./types";

export const DEMO_RESULT: AnalysisResult = {
  job_id: "demo",
  bundle_id: "lms",
  status: "done",
  error: null,
  llm_cost_usd: 0.09,
  memo: `## Executive Summary\n\nAfter evaluating three LMS proposals against institutional procurement criteria, **Brightspace by D2L** is the recommended platform. It offers the strongest combination of accessibility compliance, enterprise integrations, and transparent pricing.\n\n## Recommendation\n\n**Award to:** Brightspace (D2L) \n**Total 3-Year Cost:** $1,350,000 \n**Key Differentiator:** Full WCAG 2.1 AA certification with dedicated accessibility team and the only vendor offering a contractual uptime SLA with financial penalties.\n\n## Risk Summary\n\nBlackboard presents the highest risk profile due to vague data-ownership language and a missing DPA. Canvas is mid-tier — solid feature set but pricing escalation clauses warrant negotiation before award.`,
  proposals: [
    {
      filename: "brightspace_d2l.pdf",
      vendor_name: "Brightspace by D2L",
      extracted: {
        vendor_name: "Brightspace by D2L",
        total_cost: "$450,000/year ($1,350,000 over 3 years)",
        pricing_model: "Per-seat subscription, tiered by enrollment band",
        price_escalation: "CPI-capped at 3% annually",
        overage_fees: "None — unlimited courses included",
        contract_length: "3 years",
        renewal_terms: "Auto-renews annually unless 90-day written notice",
        termination_clause: "Termination for convenience with 90-day notice; pro-rated refund",
        liability_cap: "12 months of fees",
        data_ownership: "Institution retains full ownership; data exportable within 30 days of termination",
        data_processing_agreement: "FERPA/GDPR DPA included as Exhibit B",
        security_certifications: "SOC 2 Type II, ISO 27001, FedRAMP Moderate",
        incident_response_docs: "Incident response plan attached; 72-hour notification SLA",
        sla_uptime: "99.9% monthly uptime",
        sla_response_times: "P1: 1 hour, P2: 4 hours, P3: 24 hours",
        sla_penalties: "Service credits up to 10% of monthly fee for SLA breach",
        support_model: "24/7 phone, email, and chat; dedicated CSM for accounts > 10,000 seats",
        training_offered: "Onboarding bootcamp, admin certification, LMS user training portal",
        multi_campus_support: "Yes — multi-tenant hierarchy with campus-level admin roles",
        user_roles: "Learner, Instructor, Course Admin, Campus Admin, System Admin",
        mobile_app: "iOS and Android; offline content sync",
        accessibility_vpat: "VPAT 2.4 provided; WCAG 2.1 AA certified",
        social_listening: null,
        analytics_reporting: "Advanced analytics dashboard; xAPI/LRS integration",
        integrations: "Banner, Workday, Zoom, Turnitin, Microsoft Teams, LTI 1.3",
        sandbox_available: "Yes — persistent sandbox tenant included",
        customer_references: "3 references provided including University of Michigan and Ohio State",
        supplier_diversity: "Certified women-owned business; MA SDP registered",
        deliverables: ["Implementation plan", "Data migration guide", "Training materials", "VPAT"],
        ip_ownership: "Institution owns all course content; D2L retains platform IP",
        governing_law: "Massachusetts",
      },
      risks: [
        {
          clause: "Auto-renewal clause (Section 8.2)",
          severity: "LOW",
          explanation: "Contract auto-renews unless 90-day written notice given. Risk of unintended renewal if procurement cycle is slow.",
          recommendation: "Calendar a review 6 months before renewal date. Negotiate for 60-day notice period.",
          policy_reference: "M.G.L. c. 30B §6 — Uniform Procurement Act",
          policy_excerpt: "Contracts awarded under public procurement shall not renew automatically without affirmative action by the awarding authority prior to the expiration date.",
        },
      ],
      scores: {
        platform_functionality: { score: 9, rationale: "Full LTI 1.3, rich content editor, competency-based learning paths, and strong mobile experience." },
        accessibility_compliance: { score: 10, rationale: "WCAG 2.1 AA certified with VPAT 2.4. Only vendor with a dedicated accessibility team." },
        integration_capability: { score: 9, rationale: "Native Banner and Workday connectors; broad LTI ecosystem." },
        pricing_transparency: { score: 8, rationale: "Per-seat model is clear; CPI cap limits escalation risk." },
        security_and_compliance: { score: 9, rationale: "FedRAMP Moderate, SOC 2 Type II, ISO 27001 — strongest security posture of all vendors." },
        support_and_training: { score: 9, rationale: "24/7 support with dedicated CSM; robust training portal." },
        enterprise_readiness: { score: 9, rationale: "Multi-tenant hierarchy fits multi-campus structure well." },
        innovation_roadmap: { score: 8, rationale: "Strong AI-assisted course creation roadmap; 2025 GenAI beta announced." },
        risk_level: { score: 9, rationale: "Low risk profile. Minor auto-renewal concern easily mitigated." },
        overall: 89,
      },
    },
    {
      filename: "canvas_instructure.pdf",
      vendor_name: "Canvas by Instructure",
      extracted: {
        vendor_name: "Canvas by Instructure",
        total_cost: "$390,000/year ($1,170,000 over 3 years)",
        pricing_model: "Per-seat subscription",
        price_escalation: "Up to 5% annually at vendor's discretion",
        overage_fees: "$2.50/seat/month for overages above contracted count",
        contract_length: "3 years",
        renewal_terms: "Auto-renews for 1-year terms; 60-day notice required",
        termination_clause: "Termination for cause only in year 1; convenience from year 2",
        liability_cap: "6 months of fees",
        data_ownership: "Institution owns data; export available within 60 days",
        data_processing_agreement: "DPA available on request; not pre-attached",
        security_certifications: "SOC 2 Type II",
        incident_response_docs: "General security policy provided; no formal IR SLA",
        sla_uptime: "99.5% quarterly uptime",
        sla_response_times: "P1: 2 hours, P2: 8 hours",
        sla_penalties: "Service credits available but require written claim",
        support_model: "Business hours phone; 24/7 email only",
        training_offered: "Admin training webinars; Canvas Community access",
        multi_campus_support: "Yes — sub-accounts model",
        user_roles: "Student, Teacher, Admin, Observer, Designer",
        mobile_app: "iOS and Android",
        accessibility_vpat: "VPAT 2.3 provided; some WCAG 2.1 AA gaps noted",
        social_listening: null,
        analytics_reporting: "Canvas Data 2 (BigQuery); standard reports included",
        integrations: "Banner via partner integration; LTI 1.3; Zoom",
        sandbox_available: "Yes — beta environment included",
        customer_references: "2 references provided",
        supplier_diversity: null,
        deliverables: ["Implementation plan", "VPAT"],
        ip_ownership: "Institution owns content",
        governing_law: "Utah",
      },
      risks: [
        {
          clause: "Price escalation clause (Section 5.3)",
          severity: "MEDIUM",
          explanation: "Vendor can raise prices up to 5% annually at discretion, uncapped by index.",
          recommendation: "Negotiate to CPI cap or fixed escalation. Budget conservatively for year 2–3.",
          policy_reference: "M.G.L. c. 30B §12 — Price Adjustments",
          policy_excerpt: "Price adjustments in multi-year public contracts must be tied to a published economic index and may not be applied at the sole discretion of the vendor.",
        },
        {
          clause: "Termination restriction — Year 1 (Section 9.1)",
          severity: "MEDIUM",
          explanation: "No termination for convenience in the first 12 months. Institution is locked in regardless of performance.",
          recommendation: "Negotiate 180-day convenience termination right from contract start.",
          policy_reference: "M.G.L. c. 30B §17 — Contract Termination Rights",
          policy_excerpt: null,
        },
      ],
      scores: {
        platform_functionality: { score: 8, rationale: "Strong course authoring and widely adopted. Slightly behind on competency-based learning." },
        accessibility_compliance: { score: 7, rationale: "VPAT 2.3 has known gaps; accessibility improvements are roadmap items, not current." },
        integration_capability: { score: 8, rationale: "Good LTI support; Banner integration requires third-party middleware." },
        pricing_transparency: { score: 6, rationale: "Discretionary escalation clause and overage fees reduce predictability." },
        security_and_compliance: { score: 7, rationale: "SOC 2 Type II only; no FedRAMP or ISO 27001." },
        support_and_training: { score: 7, rationale: "24/7 email only; phone support limited to business hours." },
        enterprise_readiness: { score: 8, rationale: "Sub-accounts model works for multi-campus; lacks some admin granularity." },
        innovation_roadmap: { score: 8, rationale: "Active product roadmap; strong open-source community." },
        risk_level: { score: 6, rationale: "Two medium-severity risks require contract negotiation before award." },
        overall: 73,
      },
    },
    {
      filename: "blackboard_anthology.pdf",
      vendor_name: "Blackboard (Anthology)",
      extracted: {
        vendor_name: "Blackboard (Anthology)",
        total_cost: "$320,000/year ($960,000 over 3 years)",
        pricing_model: "Institution-wide license",
        price_escalation: "Fixed for contract term",
        overage_fees: "None stated",
        contract_length: "3 years",
        renewal_terms: "Manual renewal required",
        termination_clause: "60-day notice for either party",
        liability_cap: "Total fees paid",
        data_ownership: "Vague — 'institution retains rights to content'; no explicit data portability clause",
        data_processing_agreement: "Not provided in proposal",
        security_certifications: "SOC 2 Type I",
        incident_response_docs: "Not provided",
        sla_uptime: "99% annual",
        sla_response_times: "Best effort",
        sla_penalties: "None",
        support_model: "Email ticketing; phone for P1 only",
        training_offered: "Online knowledge base; paid onsite training available",
        multi_campus_support: "Yes",
        user_roles: "Student, Instructor, Admin",
        mobile_app: "iOS and Android (older codebase)",
        accessibility_vpat: "VPAT 2.1; WCAG 2.0 AA only",
        social_listening: null,
        analytics_reporting: "Basic reporting; advanced requires paid add-on",
        integrations: "Banner native; limited LTI 1.1 support",
        sandbox_available: "No",
        customer_references: "1 reference provided",
        supplier_diversity: null,
        deliverables: ["Implementation plan"],
        ip_ownership: "Not addressed",
        governing_law: "Virginia",
      },
      risks: [
        {
          clause: "Data ownership language (Section 11)",
          severity: "HIGH",
          explanation: "Proposal does not explicitly grant data portability rights or specify export timelines post-termination. Ambiguous 'retains rights to content' language.",
          recommendation: "Require explicit data portability clause and 30-day export window as a condition of award.",
          policy_reference: "FERPA 34 CFR §99.31 — Data Portability",
          policy_excerpt: "Institutions must ensure that education records remain accessible and returnable to the institution upon contract termination, with vendor destruction of copies documented.",
        },
        {
          clause: "Missing Data Processing Agreement",
          severity: "HIGH",
          explanation: "No DPA provided. FERPA compliance cannot be verified without a signed DPA.",
          recommendation: "Do not award without a fully executed DPA covering FERPA and applicable state privacy law obligations.",
          policy_reference: "FERPA 34 CFR Part 99",
          policy_excerpt: null,
        },
        {
          clause: "SLA — best effort response times",
          severity: "MEDIUM",
          explanation: "No contractual response time commitments for P2/P3 issues. No SLA penalties.",
          recommendation: "Require defined SLA tiers with financial penalties as a condition of negotiation.",
          policy_reference: "NIST SP 800-53 Rev. 5, SA-9 — External System Services",
          policy_excerpt: null,
        },
      ],
      scores: {
        platform_functionality: { score: 6, rationale: "Legacy platform; functional but lacking modern UX and competency-based features." },
        accessibility_compliance: { score: 5, rationale: "WCAG 2.0 AA only; falls short of the required WCAG 2.1 AA standard." },
        integration_capability: { score: 6, rationale: "Native Banner integration is a plus; LTI 1.1 is outdated." },
        pricing_transparency: { score: 8, rationale: "Lowest cost and fixed pricing is a genuine strength." },
        security_and_compliance: { score: 4, rationale: "SOC 2 Type I only; no DPA provided; incident response undocumented." },
        support_and_training: { score: 5, rationale: "Email-only support for most issues; paid training is a barrier." },
        enterprise_readiness: { score: 6, rationale: "Works at scale but admin tooling is dated." },
        innovation_roadmap: { score: 5, rationale: "Roadmap not provided; platform investment post-Anthology acquisition unclear." },
        risk_level: { score: 3, rationale: "Two HIGH-severity risks (data ownership, missing DPA) are disqualifying without remediation." },
        overall: 53,
      },
    },
  ],
  negotiation_plans: [
    {
      vendor_name: "Brightspace by D2L",
      overall_approach: "Collaborative but firm — they want this contract and scored highest; use that confidence to push on price escalation and SLA teeth.",
      priority_tactics: [
        {
          area: "Price escalation cap",
          their_position: "3% annual escalation clause in base contract",
          our_ask: "Hard cap at 2% or CPI, whichever is lower, for all 3 years",
          leverage: "Only vendor scoring above 8.0 — they have reputational incentive to close; Canvas is a credible alternative at 7.4",
        },
        {
          area: "SLA financial penalties",
          their_position: "99.9% uptime SLA with undefined penalty structure",
          our_ask: "Tiered credits: 10% monthly fee for <99.9%, 25% for <99.5%, right to terminate for <99.0%",
          leverage: "SLA penalties scored 9.0 — they know it's a strength; locking in teeth costs them little and signals good faith",
        },
        {
          area: "Implementation timeline",
          their_position: "18-month go-live estimate",
          our_ask: "12-month go-live with milestone-based payment: 30% at signing, 40% at UAT, 30% at go-live",
          leverage: "Tied payment to delivery removes their risk-free delay incentive; standard practice in higher-ed contracts",
        },
      ],
      red_lines: [
        "WCAG 2.1 AA compliance must be contractually guaranteed — not 'best effort'",
        "Data processing agreement (DPA) must be executed before contract signing",
        "Governing law must be Massachusetts courts — not Delaware",
      ],
      concessions_to_offer: [
        "3-year commitment (vs. annual renewal) in exchange for escalation cap",
        "Early payment terms (Net-15) in exchange for 2% discount",
        "Participation as a public reference customer after 12-month go-live",
      ],
      batna: "Canvas by Instructure scored 7.4/10 overall — viable alternative if D2L won't meet red lines; mention it explicitly if negotiations stall",
    },
    {
      vendor_name: "Canvas by Instructure",
      overall_approach: "Pressure-test their weaknesses — pricing escalation and missing SLA penalties are real gaps; treat this as a backup negotiation, not the primary.",
      priority_tactics: [
        {
          area: "Pricing escalation",
          their_position: "5% annual auto-escalation with no opt-out",
          our_ask: "Remove auto-escalation entirely or cap at 2%; add opt-out clause with 90-day notice",
          leverage: "Scored 6.5/10 on pricing transparency — they know it's a weakness; Brightspace offers lower escalation",
        },
        {
          area: "SLA penalties",
          their_position: "No financial penalties in current draft — uptime SLA is aspirational",
          our_ask: "Add penalty clause: minimum 5% monthly credit for any month below SLA",
          leverage: "Absence of teeth is a HIGH-risk flag per institutional policy; non-negotiable for compliance",
        },
        {
          area: "Liability cap",
          their_position: "$250,000 liability cap (25% of annual contract value)",
          our_ask: "Minimum 1× annual contract value ($1,000,000)",
          leverage: "Institutional procurement policy requires adequate coverage; $250K is below threshold for a $1M contract",
        },
      ],
      red_lines: [
        "Financial SLA penalties must be added — aspirational uptime is not acceptable",
        "Liability cap must reach $500,000 minimum before award",
        "Auto-renewal opt-out window must be extended to 120 days",
      ],
      concessions_to_offer: [
        "Pilot with one college (5,000 students) before full rollout — reduces their implementation risk",
        "Joint case study and conference presentation after year 1",
      ],
      batna: "Brightspace scored 8.2/10 overall — the preferred vendor; use this negotiation to either improve Canvas's terms or confirm Brightspace is the award",
    },
    {
      vendor_name: "Blackboard Learn Ultra",
      overall_approach: "Short session — walk in with the red lines only; this vendor is a distant third and negotiation leverage is limited without a credible award path.",
      priority_tactics: [
        {
          area: "Data ownership language",
          their_position: "Vague clause: 'institution retains ownership of content' — excludes derived data and analytics",
          our_ask: "Explicit clause covering raw content, derived data, usage analytics, and model training data",
          leverage: "HIGH-severity FERPA risk flag; DPA is missing — legally required before any data flows",
        },
        {
          area: "Liability cap",
          their_position: "$50,000 — approximately 2% of total contract value",
          our_ask: "Minimum $500,000 or 1× annual contract value",
          leverage: "Institutional policy floor; $50K is non-compliant — contract cannot proceed as written",
        },
      ],
      red_lines: [
        "Data processing agreement (DPA) must be executed — no DPA means no contract",
        "Liability cap must reach $250,000 minimum — current $50K is disqualifying",
        "SOC 2 Type II certification required within 12 months of go-live — Type I is insufficient",
      ],
      concessions_to_offer: [
        "Extended timeline to 24 months to allow SOC 2 Type II remediation",
      ],
      batna: "Both Brightspace (8.2) and Canvas (7.4) outscored Blackboard (5.2) significantly — this vendor is a last resort; do not award without full red-line compliance",
    },
  ],
};
